### ISSUE TITLE
Key file format

### ISSUE THREAD

**Issue by noraj** [VirtueSecurity/aws-extender-cli#4]
Rather than expecting a custom format

```
AccessKeyId=XXXX
SecretKey=XXXX
```

the tool could parse the format of `~/.aws/credentials`

```
[profile_name]
aws_access_key_id =  xxx
aws_secret_access_key = xxx
```

**Comment by 0xSobky** [comment]
Thanks for the suggestion, @noraj. I've created a pull request that implements your suggestion.

I believe the custom format was used initially because supported credentials are not limited to AWS API keys only but also include Google Cloud Storage API keys.

Now both formats will be accepted so it's easier to import the keys in their default format.

**Comment by noraj** [comment]
@0xSobky You're right I forgot Azure and GCP. Supporting both was the way to go.
